service: laconia-examples-serverless-vanilla

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, 'eu-west-1'}

functions:
  uppercase:
    handler: handler.handler
    events:
      - http: GET uppercase

plugins:
  - serverless-offline
